export const operatorMap: Partial<Record<Building, CharactersType | null>> = {
  quarry: 'miner',
  woodcutter: 'woodcutter',
  sawmill: 'carpenter',
  farm: 'farmer',
  mill: 'baker',
  bakery: 'baker',
  swinefarm: 'animalbreeder',
  butcher: 'butcher',
  tannery: 'butcher',
  fisherman: 'fisherman',
  vineyard: 'farmer',
  goldmine: 'miner',
  coalmine: 'miner',
  ironmine: 'miner',
  metallurgist: 'metallurgist',
  ironsmithy: 'metallurgist',
  weaponworkshop: 'carpenter',
  weaponsmithy: 'blacksmith',
  armoryworkshop: 'carpenter',
  armorsmithy: 'blacksmith',
  stables: 'animalbreeder',
  barracks: 'recruit',
  watchtower: 'recruit',
  siegeworkshop: 'carpenter',
  storehouse: null,
  marketplace: null
}
